### ISSUE TITLE
Lightning damage drop

### ISSUE THREAD

**Issue by 48004800** [Alexthw46/Ars-Elementals#18] opened 2023-02-02 04:38 UTC
ars_nouveau-1.19.2-3.9.0
Ars_Elemental-1.19.2-0.5.7.1

**Comment by 48004800** [comment] 2023-02-02 04:38
forge:43.2.3

**Comment by Alexthw46** [comment] 2023-02-02 10:37
https://gfycat.com/illcolossalboar

No it doesn't, or at least it can't be reproduced. Keep in mind that lightning doesn't count as player damage, so few types of mobs won't drop at all with that.
If you drop an item on the ground, then lightning it and it gets destroyed then it's another mod messing with it.

**Comment by 48004800** [comment] 2023-02-02 11:25
> https://gfycat.com/illcolossalboar
> 
> No it doesn't, or at least it can't be reproduced. Keep in mind that lightning doesn't count as player damage, so few types of mobs won't drop at all with that. If you drop an item on the ground, then lightning it and it gets destroyed then it's another mod messing with it.
I tried again and the result was the same
I will provide mod information
forge: 43.2.3
curios: 1.19.2-5.1.10
patchouli: 1.19.2-77
ars_nouveau-1.19.2-3.9.0
Ars_Elemental-1.19.2-0.5.7.1

**Comment by 48004800** [comment] 2023-02-02 11:26
> https://gfycat.com/illcolossalboar
> 
> No it doesn't, or at least it can't be reproduced. Keep in mind that lightning doesn't count as player damage, so few types of mobs won't drop at all with that. If you drop an item on the ground, then lightning it and it gets destroyed then it's another mod messing with it.

I tried again and the result was the same
I will provide mod information
forge: 43.2.3
curios: 1.19.2-5.1.10
patchouli: 1.19.2-77
ars_nouveau-1.19.2-3.9.0
Ars_Elemental-1.19.2-0.5.7.1

**Comment by 48004800** [comment] 2023-02-02 11:27
<img width="300" alt="image" src="https://user-images.githubusercontent.com/78255094/216312763-eee0514c-3a5e-4ca8-ae6b-38c7133df3ce.png">

**Comment by Alexthw46** [comment] 2023-02-02 11:48
Fair, apparently the feature is now only applied while i'm in the dev enviroment. I have to dig a bit on why since it was working nicely before

**Comment by Alexthw46** [comment] 2023-02-03 16:31
https://www.curseforge.com/minecraft/mc-mods/ars-elemental/files/4378328

I reverted to the old way of doing it, since i couldn't figure out what was wrong with the new. It's marked as a beta only because i want to test few things a bit better.

**Closed as completed by Alexthw46** 2023-02-03 16:31 UTC
